name: Terraform build template

on:
  workflow_call
jobs:
  terraform-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        # with:
        #   tofu_wrapper: false

      - name: Init Terraform
        run: terraform init

      - name: Vaidate Terraform
        run: terraform validate
      
      - name: Plan Terraform
        # id: plan
        run: terraform plan

      # Useless step ?
      # - name: Show outputs
      #   run: |
      #     echo ${{ steps.plan.outputs.stdout }}
      #     echo ${{ steps.plan.outputs.stderr }}
      #     echo ${{ steps.plan.outputs.exitcode }}

      - name: Apply Terraform
        run: terraform apply -auto-approve
      
      - name: Tests
        run: |
          ls -la
          ls -la .terraform/
          cat .terraform.lock.hcl
          cat terraform.tfstate
          cat test.txt
      
      # - name: Cache Terraform
      #   uses: actions/cache@v3
      #   with:
      #     path: .terraform/
      #     key: ${{ github.ref_name }}
      
      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: terraform-outputs
      #     path: outputs/
 